name: Vercel Deployment

on:
  push:
    branches: [master, main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Vercel Deploy Hook
        run: |
          echo "Triggering Vercel deployment..."
          response=$(curl -s -w "%{http_code}" -X POST "${{ secrets.VERCEL_DEPLOY_HOOK }}")
          echo "Response: $response"
          if [[ "${response: -3}" == "200" || "${response: -3}" == "201" ]]; then
            echo "✅ Deploy hook triggered successfully"
          else
            echo "❌ Deploy hook failed with response: $response"
            exit 1
          fi